"""Tests over the shipped MTL/1 examples: honesty markers, spec conformance, drift.

What these assert, and why each one exists:

1. **The demonstration marker is in every label, inside the signature, and costs nothing.**
   The generator's private key is public (seed ``bytes(range(32))``), so the documents must
   say so themselves. PROFILE §6.3 permits unknown ``mcpTrustLabel`` members explicitly, so
   the marker is conformant -- and these tests prove it by re-verifying every shipped label
   and requiring ``valid``, profile ``L0``, zero reasons and zero warnings.
2. **The generator's DID is declared in the adoption metric's own-keys file.** It is an
   AWR/2 issuer in this repository; undeclared, it counts as an adopter, and the adopter is
   us. (The binding check is in ``awr/adoption/metrics/test_adoption_metric.py`` too; this
   one fails next to the issuer that causes it.)
3. **The subject digest is stable.** ``sha256-nNR6…`` is quoted in ``PROFILE.md`` §4.5,
   ``examples/README.md`` and ``registry-integration.md``. Anything that changes it makes
   three documents wrong at once.
4. **The published pattern set is what the gate generates.** PROFILE §7.3 makes the
   pattern-set digest the thing that makes a scan label falsifiable. The table is generated by
   ``tools/regen_pattern_set.mjs`` calling ``staticScanRuleset()``, so the drift check is exact
   -- regenerate and compare bytes -- plus a build-free check that the rule *codes* still match
   ``warden/src/static-scan.ts``, and a check that the table's ``digest`` is the gate's own.
5. **The hardcoded pattern-scan findings are what the gate actually emits, with their tiers.**
   The generator cannot execute the gate (it runs with only the reference implementation on the
   path), so this test runs ``warden/dist/static-scan.js`` with node and compares. It skips,
   loudly, when node or that build is absent -- a skip is honest, an unchecked literal is not.
   It also holds the number PROFILE §7.3 argues from: every match on the benign example server
   is ``advise``-tier, so the gate score is 1.0 and nothing is blocked.

Run with::

    PYTHONPATH=awr/reference/python:awr/adoption/mcp-trust-label/tools \\
      python3 -m pytest awr/adoption/mcp-trust-label/examples/test_examples.py -q
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys

import pytest

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_HERE, "..", "..", "..", ".."))
_REFERENCE = os.path.join(_REPO, "awr", "reference", "python")
_TOOLS = os.path.normpath(os.path.join(_HERE, "..", "tools"))

for _path in (_HERE, _TOOLS, _REFERENCE):
    if _path not in sys.path:
        sys.path.insert(0, _path)

awr = pytest.importorskip("awr", reason="the AWR reference implementation is required")
pytest.importorskip("mtl_subject", reason="mtl_subject.py must be importable")

import generate  # noqa: E402

OWN_KEYS = os.path.join(_REPO, "awr", "adoption", "metrics", "own-keys.txt")
PATTERN_SET = os.path.join(_HERE, "pattern-set-argus-warden-static-scan.json")
STATIC_SCAN_TS = os.path.join(_REPO, "warden", "src", "static-scan.ts")
STATIC_SCAN_JS = os.path.join(_REPO, "warden", "dist", "static-scan.js")
GATE_ENTRY = os.path.join(_REPO, "warden", "dist", "index.js")
REGEN_PATTERN_SET = os.path.normpath(
    os.path.join(_HERE, "..", "tools", "regen_pattern_set.mjs")
)

LABELS = (
    "pass-01-pattern-scan.awr.json",
    "inconclusive-01-pattern-scan.awr.json",
    "pass-02-tool-set-observation.awr.json",
    "pass-03-tool-set-continuity.awr.json",
)

#: Quoted in PROFILE.md §4.5, examples/README.md and registry-integration.md.
PASS_SUBJECT_DIGEST = "sha256-nNR6utZJHl/EpVoffkzaYj4kA7LbJOig5Yz91lk6k1s="

NOW = "2026-07-31T12:00:00Z"


def load(name):
    with open(os.path.join(_HERE, name), "rb") as handle:
        return awr.loads(handle.read())


# ---------------------------------------------------------------------------
# 1. the demonstration marker, and that it costs the document nothing
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", LABELS)
def test_every_label_verifies_with_the_demonstration_marker_present(name):
    result = awr.verify_document(load(name), now=NOW)
    assert result["valid"], result["reasons"]
    # SPEC 10.4: the profile of a document that is not a WorkReceipt is NULL. L1/L2 are levels
    # of assurance about a unit of work, and a VerificationVerdict is not a receipt, so it
    # satisfies none of them. `profile: null` beside `valid: true` does not mean "below L0" --
    # this test asserted "L0" while two other implementations reported null, which is the
    # divergence 10.4 settled.
    assert result["profile"] is None, (
        "a VerificationVerdict has no profile (SPEC 10.4); got %r" % (result["profile"],)
    )
    assert result["profilesEvaluated"]["L1"][0]["code"] == "AWR-PROFILE-001"
    assert result["reasons"] == []
    assert result["warnings"] == [], (
        "an unknown mcpTrustLabel member is permitted by PROFILE 6.3 and must not cost the "
        "document a single warning: %s" % (result["warnings"],)
    )


@pytest.mark.parametrize("name", LABELS)
def test_every_label_says_it_is_a_demonstration_inside_its_signature(name):
    document = load(name)
    marker = document["credentialSubject"]["mcpTrustLabel"]["demonstration"]
    assert marker["isDemonstration"] is True
    assert marker["issuerPrivateKeyIsPublic"] is True
    assert "bytes(range(32))" in marker["issuerKeySeed"]
    assert "not evidence of adoption" in marker["warning"]
    # The marker is inside credentialSubject, so it is inside the signature: flipping it
    # invalidates the document rather than editing a comment.
    tampered = json.loads(json.dumps(document))
    tampered["credentialSubject"]["mcpTrustLabel"]["demonstration"]["isDemonstration"] = False
    assert not awr.verify_document(tampered, now=NOW)["valid"]


@pytest.mark.parametrize("name", LABELS)
def test_the_issuer_name_cannot_be_mistaken_for_a_real_issuer(name):
    issuer = load(name)["issuer"]
    assert issuer["id"] == generate.SCANNER_DID
    assert "DEMONSTRATION KEY" in issuer["name"]
    assert "SEED PUBLISHED" in issuer["name"]


def test_the_documented_did_is_the_one_the_published_seed_derives():
    assert awr.SigningKey.from_seed(generate.SCANNER_SEED).did == generate.SCANNER_DID
    assert generate.SCANNER_SEED == bytes(range(32))


# ---------------------------------------------------------------------------
# 2. the adoption metric must not count us
# ---------------------------------------------------------------------------


def test_the_generator_did_is_declared_in_the_adoption_own_keys_file():
    assert os.path.isfile(OWN_KEYS), (
        "awr/adoption/metrics/own-keys.txt must be committed: this generator issues AWR/2 "
        "documents, and an undeclared issuer DID is counted as an adopter"
    )
    with open(OWN_KEYS, "r", encoding="utf-8") as handle:
        text = handle.read()
    declared = [
        line.split("#", 1)[0].strip()
        for line in text.splitlines()
        if line.split("#", 1)[0].strip()
    ]
    assert generate.SCANNER_DID in declared


# ---------------------------------------------------------------------------
# 3. the digest three documents quote
# ---------------------------------------------------------------------------


def test_the_pass_subject_digest_is_the_value_the_documents_quote():
    descriptor = load("pass-01-subject-descriptor.json")
    assert awr.canonical_sri(descriptor) == PASS_SUBJECT_DIGEST
    label = load("pass-01-pattern-scan.awr.json")
    assert label["credentialSubject"]["verifiedWork"]["digestSRI"] == PASS_SUBJECT_DIGEST


def test_the_pattern_set_digest_in_the_labels_matches_the_shipped_table():
    with open(PATTERN_SET, "rb") as handle:
        table = json.loads(handle.read().decode("utf-8"))
    expected = awr.canonical_sri(table)
    for name in ("pass-01-pattern-scan.awr.json", "inconclusive-01-pattern-scan.awr.json"):
        detail = load(name)["credentialSubject"]["mcpTrustLabel"]
        assert detail["patternSet"]["digestSRI"] == expected


# ---------------------------------------------------------------------------
# 4. drift: the generated pattern table against the gate that generates it
# ---------------------------------------------------------------------------


def test_the_pattern_table_carries_a_tier_for_every_rule():
    """PROFILE 7.3 requires the published table to record each rule's tier, and forbids a
    consumer presenting an `advise` match as blocking. Neither is possible if the tiers are
    missing or if the counts the file advertises disagree with the rules it lists."""
    with open(PATTERN_SET, "r", encoding="utf-8") as handle:
        table = json.load(handle)

    # No literal version here on purpose. This test is about tiers; pinning the
    # number as well put it in direct contradiction with
    # `test_the_shipped_table_digest_is_the_gate_own_ruleset_digest`, which pins the
    # same field to whatever the gate reports. When WARDEN shipped ruleset v4 the two
    # could not both pass, and the pair read as "the table is stale" rather than
    # "one of these tests hard-codes a moving number".
    assert str(table["version"]).isdigit(), table["version"]
    rules = table["rules"]
    assert len(rules) == table["ruleCount"]
    assert all({"code", "severity", "tier", "surfaces", "source", "flags"} <= set(r) for r in rules)
    assert {r["tier"] for r in rules} <= {"block", "advise"}

    # v3: the scanned surfaces are a property of each RULE. `scannedFields` is the
    # union, derived by the generator, so a summary cannot drift from the table it
    # summarises -- which is the only reason a label reader can trust either.
    assert table["scannedFields"] == ["name", "description", "inputSchema"]
    assert {s for r in rules for s in r["surfaces"]} == set(table["scannedFields"])
    for surface, count in table["surfaceCounts"].items():
        assert count == sum(1 for r in rules if surface in r["surfaces"]), surface
    # The tool name is scanned by the phrase and hidden-payload rules and by none
    # of the noun-keyed ones: `sign_with_private_key` is a plausible tool name, and
    # refusing it would be the ruleset v1 calibration error on a new surface.
    off_name = {r["code"] for r in rules if "name" not in r["surfaces"]}
    assert off_name == {
        "TOOL_DEF_CREDENTIAL_PARAM",
        "TOOL_DEF_ENV_REFERENCE",
        "TOOL_DEF_SECRET_REQUEST",
    }, off_name

    counted = {}
    for rule in rules:
        counted[rule["tier"]] = counted.get(rule["tier"], 0) + 1
    assert counted == table["tierCounts"]

    # Regex sources are recorded so a third party can re-run the exact rule; an empty one
    # would match everything and nobody would notice from the digest alone.
    assert all(r["source"] for r in rules)


def test_the_pattern_table_names_the_same_rule_codes_as_the_gate_source():
    """A cheap check that needs no build: every code in the table appears in the gate source
    and vice versa. It cannot catch a changed regex -- that is the job of the test below,
    which runs the gate -- but it needs nothing but the .ts file, so it still holds when node
    is unavailable."""
    if not os.path.isfile(STATIC_SCAN_TS):  # pragma: no cover - WARDEN ships in this repo
        pytest.skip("warden/src/static-scan.ts is not present")
    with open(STATIC_SCAN_TS, "r", encoding="utf-8") as handle:
        source_text = handle.read()
    with open(PATTERN_SET, "r", encoding="utf-8") as handle:
        table = json.load(handle)

    in_source = set(re.findall(r'code:\s*"(TOOL_DEF_[A-Z0-9_]+)"', source_text))
    in_table = {rule["code"] for rule in table["rules"]}
    assert in_table == in_source, (
        "the published pattern set and warden/src/static-scan.ts disagree about which rules "
        "exist: only in the table %s; only in the gate %s"
        % (sorted(in_table - in_source), sorted(in_source - in_table))
    )


def test_the_pattern_table_is_byte_identical_to_what_the_gate_generates():
    """The file is generated, not transcribed, so the drift check is exact: regenerate it from
    `staticScanRuleset()` and compare bytes. A stale table means every label naming this
    pattern set names a set that was never run (PROFILE 7.3)."""
    node = shutil.which("node")
    if node is None:  # pragma: no cover - depends on the machine
        pytest.skip("node is not available, so the pattern set cannot be regenerated here")
    if not os.path.isfile(GATE_ENTRY):  # pragma: no cover - needs a built package
        pytest.skip("warden/dist/index.js is not built (cd warden && npm run build)")

    proc = subprocess.run(
        [node, REGEN_PATTERN_SET, "--check"], capture_output=True, text=True
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout


def test_the_shipped_table_digest_is_the_gate_own_ruleset_digest():
    """`digest` inside the file is the gate's own `rulesets.staticScan.digest`, which is what a
    verifier reads out of an ARGUS verdict. If the two ever differ, a label and the scan it
    describes name different rule tables while looking consistent."""
    node = shutil.which("node")
    if node is None:  # pragma: no cover - depends on the machine
        pytest.skip("node is not available")
    if not os.path.isfile(GATE_ENTRY):  # pragma: no cover - needs a built package
        pytest.skip("warden/dist/index.js is not built (cd warden && npm run build)")
    with open(PATTERN_SET, "r", encoding="utf-8") as handle:
        table = json.load(handle)

    proc = subprocess.run(
        [
            node,
            "--input-type=module",
            "-e",
            "import { staticScanRuleset } from %s;\n"
            "const r = staticScanRuleset();\n"
            "console.log(JSON.stringify({ version: r.version, digest: r.digest }));\n"
            % (json.dumps(GATE_ENTRY),),
        ],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    ruleset = json.loads(proc.stdout)
    assert table["version"] == ruleset["version"]
    assert table["digest"] == ruleset["digest"]


# ---------------------------------------------------------------------------
# 5. the hardcoded findings, checked by running the gate
# ---------------------------------------------------------------------------


def test_the_hardcoded_pattern_matches_are_what_the_gate_emits(tmp_path):
    node = shutil.which("node")
    if node is None:  # pragma: no cover - depends on the machine
        pytest.skip("node is not available, so the ARGUS gate cannot be executed here")
    if not os.path.isfile(STATIC_SCAN_JS):  # pragma: no cover - needs a built argus
        pytest.skip("warden/dist/static-scan.js is not built")

    script = tmp_path / "run-gate.mjs"
    script.write_text(
        'import { StaticScanGate } from %s;\n'
        "const tools = JSON.parse(process.argv[2]);\n"
        "const result = await new StaticScanGate().evaluate({ tools });\n"
        "console.log(JSON.stringify(result));\n" % (json.dumps(STATIC_SCAN_JS),),
        encoding="utf-8",
    )
    proc = subprocess.run(
        [node, str(script), json.dumps(generate.PATTERN_HIT_TOOLS)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    result = json.loads(proc.stdout)

    def triples(entries):
        return sorted((e["code"], e["severity"], e["tool"]) for e in entries)

    assert triples(result["findings"]) == triples(generate.PATTERN_HIT_FINDINGS), (
        "generate.py hardcodes the pattern matches it writes into the inconclusive label; "
        "the gate now emits something else: %s" % (result["findings"],)
    )

    # Every match on this benign server is advisory, which since ruleset v2 means the gate
    # score is untouched: 1.0, and the connection is refused at no blockAtSeverity. Ruleset v1
    # scored the same tool set 0.40 and blocked it at the default threshold -- the calibration
    # bug v2 fixed, and the claim examples/README.md and PROFILE 8 make from this run.
    assert all(f.get("advisory") is True for f in result["findings"]), result["findings"]
    assert result["score"] == pytest.approx(generate.PATTERN_HIT_GATE_SCORE)
    assert result["score"] == pytest.approx(1.0)
    assert not result.get("fatal")

    # PROFILE 7.3: every match entry MUST carry the matched rule's tier, and the tier it
    # carries must be the one the published table records for that code -- otherwise a reader
    # cannot tell a poisoned definition from a server that documents an API key.
    with open(PATTERN_SET, "r", encoding="utf-8") as handle:
        table = json.load(handle)
    tier_of = {rule["code"]: rule["tier"] for rule in table["rules"]}
    for entry in generate.PATTERN_HIT_FINDINGS:
        assert entry["tier"] == tier_of[entry["code"]], entry
        assert entry["tier"] == "advise"

    label = load("inconclusive-01-pattern-scan.awr.json")
    detail = label["credentialSubject"]["mcpTrustLabel"]
    assert detail["patternMatches"] == generate.PATTERN_HIT_FINDINGS
    assert all("tier" in match for match in detail["patternMatches"]), (
        "PROFILE 7.3 requires a tier on every entry: %s" % (detail["patternMatches"],)
    )
    assert label["credentialSubject"]["verdict"] == "inconclusive", (
        "PROFILE 7.3 forbids fail for this method: three matches on benign text are why"
    )
