"""Publish launch blog posts generated by the Marketing agent."""

from __future__ import annotations

import json
import logging
import re
from datetime import date
from pathlib import Path
from typing import Any

from core.paths import blog_index_path, blog_posts_dir, marketing_content_path

logger = logging.getLogger(__name__)

_ALLOWED_BLOCKS = {"p", "h2", "quote", "ul", "img", "product_link"}
_SLUG_SAFE = re.compile(r"[^a-z0-9]+")


def _normalize_body(raw: Any, *, product_id: str, product_name: str) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []
    if isinstance(raw, list):
        for item in raw:
            if not isinstance(item, dict):
                continue
            kind = str(item.get("type") or "").strip()
            if kind not in _ALLOWED_BLOCKS:
                continue
            if kind == "p" and item.get("text"):
                blocks.append({"type": "p", "text": str(item["text"]).strip()})
            elif kind == "h2" and item.get("text"):
                blocks.append({"type": "h2", "text": str(item["text"]).strip()})
            elif kind == "quote" and item.get("text"):
                blocks.append({"type": "quote", "text": str(item["text"]).strip()})
            elif kind == "ul" and isinstance(item.get("items"), list):
                items = [str(x).strip() for x in item["items"] if str(x).strip()]
                if items:
                    blocks.append({"type": "ul", "items": items})
            elif kind == "img" and item.get("src"):
                block: dict[str, Any] = {
                    "type": "img",
                    "src": str(item["src"]).strip(),
                    "alt": str(item.get("alt") or product_name).strip(),
                }
                if item.get("caption"):
                    block["caption"] = str(item["caption"]).strip()
                blocks.append(block)
            elif kind == "product_link":
                blocks.append(
                    {
                        "type": "product_link",
                        "productId": str(item.get("productId") or product_id),
                        "label": str(item.get("label") or product_name or "Product page"),
                    }
                )

    if not blocks:
        return []

    has_link = any(b.get("type") == "product_link" for b in blocks)
    if not has_link:
        blocks.append(
            {
                "type": "product_link",
                "productId": product_id,
                "label": product_name or "Product page",
            }
        )
    return blocks


def _fallback_body(marketing: dict[str, Any], *, product_id: str, product_name: str) -> list[dict[str, Any]]:
    parts: list[dict[str, Any]] = []
    tagline = str(marketing.get("tagline") or "").strip()
    long_desc = str(marketing.get("long_description") or "").strip()
    if tagline:
        parts.append({"type": "p", "text": tagline})
    if long_desc:
        parts.append({"type": "p", "text": long_desc})
    benefits = marketing.get("key_benefits")
    if isinstance(benefits, list):
        items = [str(b).strip() for b in benefits if str(b).strip()]
        if items:
            parts.append({"type": "h2", "text": "Key benefits"})
            parts.append({"type": "ul", "items": items[:5]})
    parts.append(
        {
            "type": "product_link",
            "productId": product_id,
            "label": product_name or "Product page",
        }
    )
    return parts


def launch_slug(product_id: str) -> str:
    return f"launch-{_SLUG_SAFE.sub('-', product_id.lower()).strip('-')}"


def _load_marketing(product_id: str) -> dict[str, Any] | None:
    path = marketing_content_path(product_id)
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    marketing = payload.get("marketing") if isinstance(payload, dict) else None
    return marketing if isinstance(marketing, dict) else None


def build_launch_post(product_id: str, *, product: dict[str, Any] | None = None) -> dict[str, Any] | None:
    marketing = _load_marketing(product_id)
    if not marketing:
        return None

    product_name = str(
        marketing.get("product_name")
        or (product or {}).get("name")
        or (product or {}).get("idea")
        or product_id
    ).strip()
    blog = marketing.get("blog_post") if isinstance(marketing.get("blog_post"), dict) else {}

    title = str(blog.get("title") or f"Launch: {product_name}").strip()
    excerpt = str(
        blog.get("excerpt")
        or marketing.get("short_description")
        or marketing.get("tagline")
        or title
    ).strip()[:280]
    read_min = blog.get("read_time_minutes")
    try:
        read_minutes = max(3, min(20, int(read_min)))
    except (TypeError, ValueError):
        read_minutes = 6

    tags_raw = blog.get("tags")
    tags = (
        [str(t).strip() for t in tags_raw if str(t).strip()]
        if isinstance(tags_raw, list)
        else ["product launch"]
    )
    if "product launch" not in [t.lower() for t in tags]:
        tags.insert(0, "product launch")

    body = _normalize_body(blog.get("body"), product_id=product_id, product_name=product_name)
    if not body:
        body = _fallback_body(marketing, product_id=product_id, product_name=product_name)

    return {
        "slug": launch_slug(product_id),
        "productId": product_id,
        "title": title,
        "excerpt": excerpt,
        "publishedAt": date.today().isoformat(),
        "readTime": f"{read_minutes} min",
        "tags": tags,
        "author": "AI-Factory Marketing",
        "relatedProducts": [{"productId": product_id, "label": product_name}],
        "body": body,
        "source": "marketing_agent",
    }


def _write_index(posts: list[dict[str, Any]]) -> None:
    idx_path = blog_index_path()
    idx_path.parent.mkdir(parents=True, exist_ok=True)
    posts_sorted = sorted(posts, key=lambda p: p.get("publishedAt") or "", reverse=True)
    idx_path.write_text(json.dumps({"posts": posts_sorted}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _load_index() -> list[dict[str, Any]]:
    path = blog_index_path()
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    posts = data.get("posts") if isinstance(data, dict) else data
    return [p for p in posts if isinstance(p, dict)] if isinstance(posts, list) else []


def publish_product_launch_blog_post(product_id: str, *, product: dict[str, Any] | None = None) -> bool:
    """Persist a launch blog post when a product pipeline completes."""
    post = build_launch_post(product_id, product=product)
    if not post:
        logger.info("blog: skip %s — no marketing content", product_id)
        return False

    slug = str(post["slug"])
    posts_dir = blog_posts_dir()
    posts_dir.mkdir(parents=True, exist_ok=True)
    post_path = posts_dir / f"{slug}.json"
    post_path.write_text(json.dumps(post, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    index = [p for p in _load_index() if p.get("slug") != slug]
    summary = {k: post[k] for k in ("slug", "title", "excerpt", "publishedAt", "readTime", "tags", "author", "productId") if k in post}
    index.append(summary)
    _write_index(index)

    logger.info("blog: published launch post %s for %s", slug, product_id)
    return True


def list_blog_posts() -> list[dict[str, Any]]:
    return _load_index()


def get_blog_post(slug: str) -> dict[str, Any] | None:
    path = blog_posts_dir() / f"{slug}.json"
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None
