[features]
seeds = false
skip-lint = false

[programs.localnet]
aimarket_escrow = "A1M4rk3tEscrowChanne1Paym3nt5oLProg"
aimarket_lottery = "DT6QVF7HhCQTFRCcP7V6AJpQF6ZQzEc9LQSrq85MHpFD"

[programs.devnet]
aimarket_escrow = "A1M4rk3tEscrowChanne1Paym3nt5oLProg"
aimarket_lottery = "DT6QVF7HhCQTFRCcP7V6AJpQF6ZQzEc9LQSrq85MHpFD"

[programs.mainnet]
aimarket_escrow = "A1M4rk3tEscrowChanne1Paym3nt5oLProg"
aimarket_lottery = "DT6QVF7HhCQTFRCcP7V6AJpQF6ZQzEc9LQSrq85MHpFD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json tests/**/*.ts"
