"""The dependency gates must fail closed on anything they cannot read or check.

Every behavioural test runs against both scanners: the parent tree's, and PingBlip's
own copy, which is the one deploy_pingblip.sh gates on. A parity test keeps the two
from drifting apart again. No test contacts OSV.
"""
import ast
import importlib.util
import io
import json
import urllib.error
import urllib.request
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
SCANNERS = {"root": REPO / "scripts" / "dependency_scan.py",
            "pingblip": REPO / "pingblip" / "scripts" / "dependency_scan.py"}


def load(which):
    spec = importlib.util.spec_from_file_location(f"dependency_scan_{which}", SCANNERS[which])
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(params=sorted(SCANNERS))
def scan(request):
    return load(request.param)


def write(root, files):
    for name, text in files.items():
        (root / name).parent.mkdir(parents=True, exist_ok=True)
        (root / name).write_text(text)
    return root


def osv(monkeypatch, batch=None, advisories=None):
    """Answer OSV from memory: batch=None means offline, a missing advisory is a 404."""
    calls = []

    def urlopen(req, timeout=None):
        calls.append(req)
        if isinstance(req, urllib.request.Request):
            if batch is None:
                raise urllib.error.URLError("offline")
            return io.BytesIO(json.dumps(batch).encode())
        vid = req.rsplit("/", 1)[-1]
        if vid not in (advisories or {}):
            raise urllib.error.HTTPError(req, 404, "not found", {}, None)
        return io.BytesIO(json.dumps(advisories[vid]).encode())

    monkeypatch.setattr(urllib.request, "urlopen", urlopen)
    return calls


def gate(scan, monkeypatch, tree, *extra):
    monkeypatch.setattr("sys.argv", ["dependency_scan.py", str(tree), *extra])
    return scan.main()


DJANGO = {"requirements.txt": "django==2.2.0\n"}
HIT = {"results": [{"vulns": [{"id": "GHSA-synthetic"}]}]}


# -- OSV availability: PingBlip's copy used to skip a failed batch and blank a failed advisory.

def test_unavailable_database_fails_gate(scan, monkeypatch, tmp_path, capsys):
    osv(monkeypatch, batch=None)
    assert gate(scan, monkeypatch, write(tmp_path, DJANGO)) == 2
    assert "OK:" not in capsys.readouterr().out


@pytest.mark.parametrize("batch", [{"results": []}, {"results": [None]},
                                   {"results": [{"next_page_token": "more"}]}])
def test_truncated_or_paginated_batch_fails_gate(scan, monkeypatch, tmp_path, batch):
    osv(monkeypatch, batch=batch)
    assert gate(scan, monkeypatch, write(tmp_path, DJANGO)) == 2


def test_unavailable_advisory_fails_gate(scan, monkeypatch, tmp_path, capsys):
    osv(monkeypatch, batch=HIT, advisories={})
    assert gate(scan, monkeypatch, write(tmp_path, DJANGO)) == 2
    assert "OK:" not in capsys.readouterr().out


def test_advisory_without_severity_fails_gate(scan, monkeypatch, tmp_path):
    osv(monkeypatch, batch=HIT, advisories={"GHSA-synthetic": {"id": "GHSA-synthetic"}})
    assert gate(scan, monkeypatch, write(tmp_path, DJANGO)) == 2


def test_complete_clean_answer_passes(scan, monkeypatch, tmp_path):
    osv(monkeypatch, batch={"results": [{}]})
    assert gate(scan, monkeypatch, write(tmp_path, DJANGO)) == 0


# -- Manifests: whatever cannot be read must not come out as "no manifests found".

UV_LOCK = """\
version = 1
revision = 3

[[package]]
name = "demo"
version = "0.1.0"
source = { editable = "." }

[[package]]
name = "psycopg"
version = "3.3.4"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "vendored"
version = "1.0"
source = { git = "https://example.invalid/vendored?rev=abc#abc" }
"""
CARGO_LOCK = """\
version = 4

[[package]]
name = "awr"
version = "2.0.0"

[[package]]
name = "sha2"
version = "0.10.8"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "forked"
version = "0.1.0"
source = "git+https://example.invalid/forked#abc"
"""
PUBSPEC_LOCK = """\
# Generated by pub
packages:
  archive:
    dependency: "direct main"
    description:
      name: archive
      sha256: a96e8b390886ee8abb49b7bd3ac8df6f451c621619f52a26e815fdcf568959ff
      url: "https://pub.dev"
    source: hosted
    version: "4.0.9"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  aicom_desktop_core:
    dependency: "direct main"
    description:
      path: "../packages/aicom_desktop_core"
      relative: true
    source: path
    version: "0.2.1"
sdks:
  dart: ">=3.11.1 <4.0.0"
"""


def test_pins_with_extras_are_scanned(scan, tmp_path):
    write(tmp_path, {"requirements.txt": "uvicorn[standard]==0.30.6\n"
                                         'PyJWT[crypto] == 2.13.0 ; python_version >= "3.8"\n'
                                         "psycopg[binary,pool]==3.3.4\n"})
    packages, _ = scan.collect(tmp_path, respect_independent=False)
    assert packages == {("PyPI", "uvicorn", "0.30.6"), ("PyPI", "PyJWT", "2.13.0"),
                        ("PyPI", "psycopg", "3.3.4")}


def test_uv_cargo_and_pub_lockfiles_are_read(scan, tmp_path):
    if scan.tomllib is None:
        pytest.skip("no TOML parser on this interpreter")
    write(tmp_path, {"py/uv.lock": UV_LOCK, "rs/Cargo.lock": CARGO_LOCK, "dart/pubspec.lock": PUBSPEC_LOCK})
    packages, owners = scan.collect(tmp_path, respect_independent=False)
    assert packages == {("PyPI", "psycopg", "3.3.4"), ("crates.io", "sha2", "0.10.8"),
                        ("Pub", "archive", "4.0.9")}
    assert owners[("Pub", "archive", "4.0.9")] == {"dart"}


BROKEN = {
    "package-lock with a trailing comma": {
        "package-lock.json": '{"lockfileVersion": 3, "packages": {"node_modules/next": {"version": "15.5.4"},}}'},
    "package-lock that is not an object": {"package-lock.json": "[]"},
    "pin the parser cannot read": {"requirements.txt": "flask===2.0.1\n"},
    "uv.lock that is not TOML": {"uv.lock": 'version = 1\n[[package]\nname = "x"\n'},
    "uv.lock with an unknown source": {"uv.lock": '[[package]]\nname = "x"\nversion = "1"\nsource = { svn = "x" }\n'},
    "Cargo.lock with an unknown source": {"Cargo.lock": '[[package]]\nname = "x"\nversion = "1"\nsource = "svn+x"\n'},
    "pubspec.lock hosted package without a version": {
        "pubspec.lock": "packages:\n  archive:\n    dependency: transitive\n    source: hosted\n"},
    "pubspec.lock in another layout": {"pubspec.lock": "packages:\n  archive:\n    source hosted\n"},
}


@pytest.mark.parametrize("case", sorted(BROKEN))
def test_unreadable_manifest_fails_gate(scan, monkeypatch, tmp_path, capsys, case):
    if scan.tomllib is None and "lock" in case and ("uv" in case or "Cargo" in case):
        pytest.skip("no TOML parser on this interpreter")
    calls = osv(monkeypatch, batch={"results": [{}]})
    assert gate(scan, monkeypatch, write(tmp_path, BROKEN[case])) == 2
    assert "no manifests found" not in capsys.readouterr().out
    assert calls == []


def test_toml_lockfile_without_a_toml_parser_fails_gate(scan, monkeypatch, tmp_path):
    monkeypatch.setattr(scan, "tomllib", None)
    osv(monkeypatch, batch={"results": [{}]})
    assert gate(scan, monkeypatch, write(tmp_path, {"uv.lock": UV_LOCK})) == 2


def test_upstream_checkouts_are_skipped_only_on_a_bare_run(scan, tmp_path):
    write(tmp_path, {"hub/requirements.txt": "b==1.0\n",
                     "hub/.upstreams/runtime/requirements.txt": "a==1.0\n"})
    bare, _ = scan.collect(tmp_path, respect_independent=True)
    explicit, _ = scan.collect(tmp_path / "hub", respect_independent=False)
    assert bare == {("PyPI", "b", "1.0")}
    assert explicit == {("PyPI", "a", "1.0"), ("PyPI", "b", "1.0")}


def test_every_manifest_the_gates_scan_is_readable():
    """What CI and deploy_pingblip.sh actually scan must parse, or they go red for it."""
    root, pingblip = load("root"), load("pingblip")
    if root.tomllib is None:
        pytest.skip("no TOML parser on this interpreter")
    packages, _ = root.collect(REPO, respect_independent=True)
    assert {eco for eco, _, _ in packages} >= {"npm", "PyPI", "crates.io", "Pub"}
    pingblip.collect(REPO / "pingblip", respect_independent=False)


def test_pub_reader_agrees_with_a_yaml_parser():
    yaml = pytest.importorskip("yaml")
    scan = load("root")
    locks = [p for p in REPO.rglob("pubspec.lock")
             if not {"node_modules", ".claude"} & set(p.relative_to(REPO).parts)]
    assert locks
    for lock in locks:
        data = yaml.safe_load(lock.read_text())
        expected = {("Pub", name, str(meta["version"])) for name, meta in data["packages"].items()
                    if meta["source"] == "hosted"}
        assert scan.pub_packages(lock) == expected, lock


# -- Severity: a CVSS vector alone must be scored, not reported as unknown.

@pytest.mark.parametrize("vector,score", [
    ("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", 9.8),
    ("CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", 9.8),
    ("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H", 10.0),
    ("CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H", 8.8),
    ("CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H", 8.1),
    ("CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N", 6.1),
    ("CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N", 5.5),
    ("CVSS:3.1/AV:P/AC:H/PR:H/UI:R/S:U/C:L/I:N/A:N", 1.6),
    ("CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:N", 0.0),
    ("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N", None),
    ("CVSS:3.1/AV:N/AC:L", None),
])
def test_cvss3_base_score(scan, vector, score):
    assert scan.cvss3_score(vector) == score


def test_vector_only_critical_advisory_blocks_as_critical(scan, monkeypatch, tmp_path, capsys):
    record = {"id": "PYSEC-synthetic",
              "severity": [{"type": "CVSS_V3", "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"}]}
    assert scan.severity_of(record) == "CRITICAL"
    osv(monkeypatch, batch={"results": [{"vulns": [{"id": "PYSEC-synthetic"}]}]},
        advisories={"PYSEC-synthetic": record})
    assert gate(scan, monkeypatch, write(tmp_path, DJANGO), "--level", "critical") == 1
    assert "CRITICAL" in capsys.readouterr().out


def test_unscored_vector_keeps_the_gate_closed(scan):
    record = {"severity": [{"type": "CVSS_V4", "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N"}]}
    assert scan.severity_of(record) == "UNKNOWN"


# -- Parity: the copy deploy_pingblip.sh runs must not drift from the parent scanner.

LOCAL = {"SKIP_DIRS", "INDEPENDENT", "_unpublished_root_dirs"}


def definitions(path):
    out = {}
    for node in ast.parse(path.read_text()).body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            out[node.name] = ast.dump(node)
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            for target in node.targets if isinstance(node, ast.Assign) else [node.target]:
                if isinstance(target, ast.Name):
                    out[target.id] = ast.dump(node.value) if node.value else None
        elif isinstance(node, ast.Try):
            out["<optional imports>"] = ast.dump(node)
    return {k: v for k, v in out.items() if k not in LOCAL}


def test_pingblip_scanner_logic_matches_the_parent_scanner():
    root, pingblip = definitions(SCANNERS["root"]), definitions(SCANNERS["pingblip"])
    assert sorted(pingblip) == sorted(root)
    assert [name for name in root if root[name] != pingblip[name]] == []
