#!/usr/bin/env bash
# Stand up the bubble's own capability satellites.
#
# The bubble hub was a federation index with nothing to index: 1 local capability, 0 peers,
# against the live hub's 0 local and 99 federated across 7 sources. From the inside that is
# the most obvious way to tell the two apart, and the invariant is that you cannot.
#
# WHY THEY LIVE BEHIND THE HUB'S OWN PUBLIC NAME, on paths rather than on the docker bridge:
# the crawler's SSRF guard (`crawler._is_private_url`) rejects 127.0.0.0/8 and 172.16.0.0/12
# outright, with no env override and no realm exemption, and the ROUTED INVOKE goes through
# the same check (api.py calls `safe_post` without `invoke=True`). The two documented private
# -address escapes — AIMARKET_ALLOW_LOCAL_PUBLISH and AIMARKET_INVOKE_HOST_GATEWAY — are
# honoured only for locally PUBLISHED capabilities, never for federation. So a bubble peer on
# a private address can be neither crawled nor invoked. Giving each satellite a path under
# `https://uni.modelmarket.dev` makes the host resolve to a public IP, which the guard
# accepts, while the packets never leave the machine: exactly the compromise the bubble hub
# itself already makes, and it needs no weakening of a security control.
#
# Idempotent. Re-run it after changing a catalogue; keys in /var/lib/uni-satellites survive,
# which matters because the hub PINS a peer's key on first contact and refuses it forever
# after if it changes.
set -euo pipefail

REPO="${REPO:-/root/claudecode/aicom}"
PUBLIC_BASE="${PUBLIC_BASE:-https://uni.modelmarket.dev}"
KEY_DIR="${KEY_DIR:-/var/lib/uni-satellites}"
ENV_DIR="${ENV_DIR:-/etc/uni-satellites}"
PYTHON="${PYTHON:-/usr/bin/python3}"

# name:port — ports are 9301+. 9330 is taken on this host by something else; stay clear.
SATELLITES=(
  "khronos:9301"
  "kyma:9302"
  "psephos:9303"
  "stoicheion:9304"
  "diktyon:9305"
  "horizon:9306"
)

mkdir -p "$KEY_DIR" "$ENV_DIR" /etc/nginx/snippets
chmod 700 "$KEY_DIR"

cat > /etc/systemd/system/uni-satellite@.service <<'UNIT'
[Unit]
Description=UNI bubble capability satellite %i
After=network.target

[Service]
Type=simple
# `python3 -m uni.satellite` needs the monorepo root on sys.path, which WorkingDirectory
# provides under -m.
WorkingDirectory=/root/claudecode/aicom
EnvironmentFile=/etc/uni-satellites/%i.env
ExecStart=/usr/bin/python3 -m uni.satellite
Restart=always
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
# The key directory is the only state, and losing it takes the satellite out of the
# federation permanently (the hub's pin never matches again).
ReadWritePaths=/var/lib/uni-satellites

[Install]
WantedBy=multi-user.target
UNIT

SNIPPET=/etc/nginx/snippets/uni-satellites.conf
: > "$SNIPPET"
cat >> "$SNIPPET" <<'HEAD'
# The bubble's satellites, generated by deploy/uni-satellites.sh — do not edit by hand.
#
# `^~` so these win over any regex location, and proxy_pass with a trailing slash so the
# /sat/<name> prefix is stripped and the satellite sees /.well-known/... as its own root.
# The exact-match block exists because the crawler is configured with follow_redirects=False:
# nginx's automatic 301 from /sat/<name> to /sat/<name>/ would be read as a failed fetch.
HEAD

for entry in "${SATELLITES[@]}"; do
  name="${entry%%:*}"
  port="${entry##*:}"

  cat > "$ENV_DIR/$name.env" <<ENVFILE
UNI_SAT_CATALOGUE=$name
UNI_SAT_PUBLIC_URL=$PUBLIC_BASE/sat/$name
UNI_SAT_HOST=127.0.0.1
UNI_SAT_PORT=$port
UNI_SAT_KEY=$KEY_DIR/$name.pem
ENVFILE

  cat >> "$SNIPPET" <<NGINX

location = /sat/$name {
    proxy_pass http://127.0.0.1:$port/;
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-Proto \$scheme;
}
location ^~ /sat/$name/ {
    proxy_pass http://127.0.0.1:$port/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 120s;
}
NGINX
done

systemctl daemon-reload
for entry in "${SATELLITES[@]}"; do
  name="${entry%%:*}"
  systemctl enable --now "uni-satellite@$name" >/dev/null
done

nginx -t
systemctl reload nginx

echo
echo "satellite            state      capabilities  signer_public_key"
for entry in "${SATELLITES[@]}"; do
  name="${entry%%:*}"
  port="${entry##*:}"
  for _ in $(seq 1 20); do
    curl -sf --max-time 2 "http://127.0.0.1:$port/health" >/dev/null && break
    sleep 0.5
  done
  state=$(systemctl is-active "uni-satellite@$name" || true)
  read -r count key < <("$PYTHON" - "$port" <<'PY'
import json, sys, urllib.request
port = sys.argv[1]
try:
    with urllib.request.urlopen(
            f"http://127.0.0.1:{port}/.well-known/ai-market.json", timeout=5) as r:
        d = json.load(r)
    print(d.get("capabilities_count"), d.get("signer_public_key"))
except Exception as exc:  # noqa: BLE001
    print("-", f"unreachable: {type(exc).__name__}")
PY
)
  printf "%-20s %-10s %-13s %s\n" "$name" "$state" "$count" "$key"
done

echo
echo "Next: point the hub at them. The seed list must be non-empty — an EMPTY"
echo "AIMARKET_SEED_LIST falls back to the committed file, which names the LIVE"
echo "satellites, and the realm seal now refuses that."
