// Regenerate examples/pattern-set-argus-warden-static-scan.json from the shipping gate.
//
//   node awr/adoption/mcp-trust-label/tools/regen_pattern_set.mjs [--check]
//
// PROFILE.md §7.3 makes the pattern-set digest the thing that makes a scan label falsifiable.
// A digest over a hand transcription binds to the transcription, so this file is GENERATED by
// calling `staticScanRuleset()` in @aimarket/warden — the same function the gate itself calls
// to stamp `verdict.rulesets.staticScan` — and never edited by hand.
//
// `--check` writes nothing and exits non-zero if the committed file has drifted, which is what
// CI and test_examples.py want.
//
// Requires the firewall package to be built: `cd warden && npm run build`.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..", "..", "..");
const target = join(here, "..", "examples", "pattern-set-argus-warden-static-scan.json");
const gate = join(repo, "warden", "dist", "index.js");

if (!existsSync(gate)) {
  console.error(`error: ${gate} is not built — run: cd warden && npm run build`);
  process.exit(2);
}
const { staticScanRuleset } = await import(gate);
const ruleset = staticScanRuleset();

const tierCounts = {};
for (const rule of ruleset.rules) tierCounts[rule.tier] = (tierCounts[rule.tier] ?? 0) + 1;

// Ruleset v3 made the scanned surfaces a property of each RULE, so this file's
// `scannedFields` is derived from the table rather than restated here: a rule that
// starts or stops looking at a surface must not be able to disagree with the
// summary a label reader trusts.
const SURFACE_ORDER = ["name", "description", "inputSchema"];
const scanned = new Set();
for (const rule of ruleset.rules) for (const surface of rule.surfaces ?? []) scanned.add(surface);
const scannedFields = SURFACE_ORDER.filter((surface) => scanned.has(surface));
const surfaceCounts = {};
for (const surface of scannedFields) {
  surfaceCounts[surface] = ruleset.rules.filter((r) => (r.surfaces ?? []).includes(surface)).length;
}

const document = {
  id: "urn:awr:mtl:1:patternset:argus-warden-static-scan",
  source: "warden/src/static-scan.ts",
  note:
    "GENERATED from the shipping ARGUS WARDEN static-scan gate by calling staticScanRuleset(); " +
    "do not hand-edit. This file exists so that a pattern-set digest is reproducible: two MTL " +
    "labels are comparable only when they name the same pattern set. Ruleset v2 gave every rule " +
    "a TIER: a `block` rule can refuse a connection, an `advise` rule is reported and never " +
    "blocks at any blockAtSeverity and never affects the score. A label that presents an " +
    "advisory hit as a blocking finding misrepresents the scan. The `severity` values are the " +
    "gate own and MTL/1 attaches no safety meaning to them. Ruleset v3 added SURFACES: every rule " +
    "declares whether it runs against the tool name, the description or the input schema. The tool " +
    "name was scanned by nothing before v3; noun-keyed rules stay off it deliberately, because they " +
    "match ordinary identifiers. Ruleset v4 added GUARDS and re-tiered on field evidence: a guard " +
    "inspects a match in context and drops it when the match is not the thing the rule looks for " +
    "(a mention rather than an instruction, a detection rather than a request, an identifier " +
    "fragment rather than a secret). Two rules with the same regex and different guards are " +
    "different rulesets, so `guards` is inside the digest. Comparing a v4 label with a v3 one " +
    "compares different scans: v4 blocks on 15 rules where v3 blocked on 18.",
  version: ruleset.version,
  digest: ruleset.digest,
  digestNote:
    "sha256 over the RFC 8785 canonical form of {version, rules}, rules sorted by code-unit " +
    'comparison. Recompute with: node -e "import(\'./warden/dist/index.js\')' +
    '.then(m=>console.log(m.staticScanRuleset().digest))", or regenerate this whole file with ' +
    "awr/adoption/mcp-trust-label/tools/regen_pattern_set.mjs.",
  scannedFields,
  surfaceCounts,
  ruleCount: ruleset.rules.length,
  tierCounts,
  rules: ruleset.rules,
};

const text = JSON.stringify(document, null, 1) + "\n";

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current === text) {
    console.log(`ok — pattern set matches the gate (${document.ruleCount} rules, ${document.digest})`);
    process.exit(0);
  }
  console.error("DRIFT — the committed pattern set is not what the gate produces.");
  console.error("Regenerate: node awr/adoption/mcp-trust-label/tools/regen_pattern_set.mjs");
  console.error("Then reissue the labels, because their patternSet.digestSRI covers this file:");
  console.error("  PYTHONPATH=awr/reference/python:awr/adoption/mcp-trust-label/tools \\");
  console.error("    python3 awr/adoption/mcp-trust-label/examples/generate.py");
  process.exit(1);
}

writeFileSync(target, text);
console.log(`wrote ${target}`);
console.log(`  version ${document.version} · ${document.ruleCount} rules · ${JSON.stringify(tierCounts)}`);
console.log(`  surfaces ${JSON.stringify(surfaceCounts)}`);
console.log(`  gate digest ${document.digest}`);
console.log("Reissue the labels next: their patternSet.digestSRI is taken over this file.");
