#!/usr/bin/env python3
"""Re-open an on-chain AIMarketEscrow channel for a factory product and rebind Hub.

Escrow channels expire after 24h. Hub then answers every paid invoke with
``payment_authorization_required: escrow channel … is not open on chain``, and
Sentinel soft-mesh stays UNKNOWN forever.

Usage (on the factory host, inside aicom-app or with data/ reachable)::

    python3 scripts/reopen_product_escrow_channel.py prod-bdb1634806de
    python3 scripts/reopen_product_escrow_channel.py prod-bdb1634806de --deposit 1.0

Writes ``data/state/<pid>/aimarket_participant.env`` with the new
``AIMARKET_ESCROW_CHANNEL`` + ``AIMARKET_PAYMENT_CHANNEL`` (+ secret). Republish
the product so Vercel picks up the env via ``mesh_env()``.
"""

from __future__ import annotations

import argparse
import json
import secrets
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEFAULT_USDC = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
def _registry_escrow() -> str:
    """The deployed escrow, from config/deployments/base-mainnet.json.

    This was a hardcoded default. The 2026-09-04 redeploy moved the escrow, and a script
    that reopens or funds a CHANNEL against the wrong contract does not fail loudly — it
    reads a contract that has no such channel and reports it closed.
    """
    import json as _json
    from pathlib import Path as _Path

    for candidate in (
        _Path(__file__).resolve().parents[1] / "config" / "deployments" / "base-mainnet.json",
        _Path(__file__).resolve().parents[1] / "aimarket-hub" / "aimarket_hub" / "deployments" / "base-mainnet.json",
    ):
        try:
            data = _json.loads(candidate.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        addr = ((data.get("contracts") or {}).get("AIMarketEscrow") or "").strip()
        if addr:
            return addr
    return ""


DEFAULT_ESCROW = _registry_escrow()
DEFAULT_RPC = "https://mainnet.base.org"
DEFAULT_HUB = "https://modelmarket.dev"
TOKEN_DECIMALS = 6


def _load_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _write_env(path: Path, env: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Preserve a stable key order for the fields we care about; keep extras.
    preferred = [
        "AIMARKET_HUB_URL",
        "AIMARKET_WALLET_ADDRESS",
        "AIMARKET_WALLET_KEY",
        "AIMARKET_PAYMENT_CHANNEL",
        "AIMARKET_PAYMENT_CHANNEL_SECRET",
        "AIMARKET_SANDBOX_VISITOR",
        "AIMARKET_CHANNEL_DEPOSIT_USD",
        "AIMARKET_ESCROW_CHANNEL",
        "AIMARKET_ESCROW_HUB_ADDRESS",
        "AIMARKET_ESCROW_CONTRACT",
    ]
    lines: list[str] = [
        "# Regenerated by scripts/reopen_product_escrow_channel.py — do not hand-edit secrets into git.",
    ]
    seen: set[str] = set()
    for key in preferred:
        if key in env and env[key]:
            lines.append(f"{key}={env[key]}")
            seen.add(key)
    for key, val in sorted(env.items()):
        if key in seen or not val:
            continue
        lines.append(f"{key}={val}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _hub_open(
    hub: str,
    *,
    wallet: str,
    escrow_channel: str,
    deposit_usd: float,
) -> dict:
    body = {
        "deposit_usd": deposit_usd,
        "token": "USDC",
        "chain": "base",
        "wallet": wallet,
        "escrow_channel_id": escrow_channel,
    }
    data = json.dumps(body).encode()
    req = urllib.request.Request(
        hub.rstrip("/") + "/ai-market/v2/channel/open",
        data=data,
        method="POST",
        headers={"content-type": "application/json", "user-agent": "reopen-product-escrow/1.0"},
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return {"status": resp.status, "body": json.loads(resp.read() or b"{}")}
    except urllib.error.HTTPError as exc:
        raw = exc.read() or b"{}"
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            parsed = {"error": raw.decode("utf-8", "replace")[:500]}
        return {"status": exc.code, "body": parsed}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("product_id")
    ap.add_argument("--deposit", type=float, default=1.0, help="USDC to lock (min $1)")
    ap.add_argument("--rpc", default=DEFAULT_RPC)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    from core.paths import resolve_data_root
    from eth_account import Account
    from web3 import Web3

    data = Path(resolve_data_root())
    env_path = data / "state" / args.product_id / "aimarket_participant.env"
    env = _load_env(env_path)
    if not env.get("AIMARKET_WALLET_KEY") or not env.get("AIMARKET_WALLET_ADDRESS"):
        print(f"missing wallet in {env_path}", file=sys.stderr)
        return 2

    wallet = Web3.to_checksum_address(env["AIMARKET_WALLET_ADDRESS"])
    key = env["AIMARKET_WALLET_KEY"]
    acct = Account.from_key(key)
    if acct.address.lower() != wallet.lower():
        print(f"key/address mismatch: {acct.address} vs {wallet}", file=sys.stderr)
        return 2

    escrow = Web3.to_checksum_address(env.get("AIMARKET_ESCROW_CONTRACT") or DEFAULT_ESCROW)
    usdc = Web3.to_checksum_address(DEFAULT_USDC)
    hub_url = (env.get("AIMARKET_HUB_URL") or DEFAULT_HUB).rstrip("/")
    deposit_units = int(round(float(args.deposit) * 10**TOKEN_DECIMALS))
    if deposit_units < 10**TOKEN_DECIMALS:
        print("deposit must be >= $1 (MIN_DEPOSIT)", file=sys.stderr)
        return 2

    channel_id = "0x" + secrets.token_hex(32)
    print(f"product={args.product_id}")
    print(f"wallet={wallet}")
    print(f"new_escrow_channel={channel_id}")
    print(f"deposit_usd={args.deposit} units={deposit_units}")
    print(f"escrow={escrow}")

    if args.dry_run:
        print("dry-run: no txs")
        return 0

    w3 = Web3(Web3.HTTPProvider(args.rpc))
    if not w3.is_connected():
        print(f"RPC not connected: {args.rpc}", file=sys.stderr)
        return 1

    erc20_abi = [
        {
            "name": "approve",
            "type": "function",
            "stateMutability": "nonpayable",
            "inputs": [{"name": "spender", "type": "address"}, {"name": "amount", "type": "uint256"}],
            "outputs": [{"type": "bool"}],
        },
        {
            "name": "balanceOf",
            "type": "function",
            "stateMutability": "view",
            "inputs": [{"name": "a", "type": "address"}],
            "outputs": [{"type": "uint256"}],
        },
        {
            "name": "allowance",
            "type": "function",
            "stateMutability": "view",
            "inputs": [{"name": "o", "type": "address"}, {"name": "s", "type": "address"}],
            "outputs": [{"type": "uint256"}],
        },
    ]
    escrow_abi = [
        {
            "name": "openChannel",
            "type": "function",
            "stateMutability": "nonpayable",
            "inputs": [
                {"name": "channelId", "type": "bytes32"},
                {"name": "token", "type": "address"},
                {"name": "depositAmount", "type": "uint256"},
            ],
            "outputs": [{"name": "expiresAt", "type": "uint256"}],
        },
        {
            "name": "isChannelOpen",
            "type": "function",
            "stateMutability": "view",
            "inputs": [{"name": "channelId", "type": "bytes32"}],
            "outputs": [{"type": "bool"}],
        },
    ]
    token = w3.eth.contract(address=usdc, abi=erc20_abi)
    contract = w3.eth.contract(address=escrow, abi=escrow_abi)

    bal = token.functions.balanceOf(wallet).call()
    eth_bal = w3.eth.get_balance(wallet)
    print(f"USDC={bal / 1e6} ETH={w3.from_wei(eth_bal, 'ether')}")
    if bal < deposit_units:
        print(f"insufficient USDC: have {bal / 1e6}, need {args.deposit}", file=sys.stderr)
        return 1
    if eth_bal < w3.to_wei(0.00005, "ether"):
        print(f"ETH balance too low for gas: {w3.from_wei(eth_bal, 'ether')}", file=sys.stderr)
        return 1

    def _send(fn) -> str:
        # Wait for prior txs so nonce is stable; price from live baseFee so Base
        # does not reject with replacement transaction underpriced.
        time.sleep(2)
        nonce = w3.eth.get_transaction_count(wallet, "pending")
        base = w3.eth.get_block("latest").get("baseFeePerGas") or w3.to_wei(0.02, "gwei")
        priority = max(w3.to_wei(0.05, "gwei"), int(base * 0.1) or 1)
        max_fee = max(int(base) * 2 + int(priority), w3.to_wei(0.5, "gwei"))
        tx = fn.build_transaction(
            {
                "from": wallet,
                "nonce": nonce,
                "chainId": 8453,
                "gas": 300_000,
                "maxFeePerGas": max_fee,
                "maxPriorityFeePerGas": priority,
            }
        )
        signed = acct.sign_transaction(tx)
        raw = getattr(signed, "raw_transaction", None) or signed.rawTransaction
        tx_hash = w3.eth.send_raw_transaction(raw)
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=180)
        if receipt.status != 1:
            raise RuntimeError(f"tx reverted: {tx_hash.hex()}")
        return tx_hash.hex()

    allow = token.functions.allowance(wallet, escrow).call()
    if allow < deposit_units:
        print("approve USDC…")
        print("  tx", _send(token.functions.approve(escrow, deposit_units)))
    else:
        print(f"allowance already {allow / 1e6} USDC")

    cid_bytes = bytes.fromhex(channel_id[2:])
    print("openChannel…")
    open_tx = _send(contract.functions.openChannel(cid_bytes, usdc, deposit_units))
    print("  tx", open_tx)
    open_ok = False
    for _ in range(8):
        time.sleep(1.5)
        try:
            if contract.functions.isChannelOpen(cid_bytes).call():
                open_ok = True
                break
        except Exception as exc:
            print(f"  isChannelOpen probe: {exc}")
    if not open_ok:
        print("isChannelOpen=false after openChannel", file=sys.stderr)
        return 1
    print("on-chain Open ✓")

    opened = _hub_open(hub_url, wallet=wallet, escrow_channel=channel_id, deposit_usd=args.deposit)
    print("hub channel/open →", opened["status"], json.dumps(opened["body"], default=str)[:400])
    body = opened["body"] if isinstance(opened["body"], dict) else {}
    channel = body.get("channel") if isinstance(body.get("channel"), dict) else body
    payment_id = str(channel.get("channel_id") or body.get("channel_id") or "")
    payment_secret = str(channel.get("channel_secret") or body.get("channel_secret") or "")
    if opened["status"] != 200 or not payment_id:
        print("hub did not open a payment channel — env not updated", file=sys.stderr)
        return 1

    env["AIMARKET_ESCROW_CHANNEL"] = channel_id
    env["AIMARKET_ESCROW_CONTRACT"] = escrow
    env["AIMARKET_PAYMENT_CHANNEL"] = payment_id
    env["AIMARKET_PAYMENT_CHANNEL_SECRET"] = payment_secret
    env["AIMARKET_CHANNEL_DEPOSIT_USD"] = str(args.deposit)
    env.setdefault("AIMARKET_HUB_URL", hub_url)
    _write_env(env_path, env)
    print(f"wrote {env_path}")
    print(f"AIMARKET_PAYMENT_CHANNEL={payment_id}")
    print("next: republish product so Vercel mesh_env injects the new channel")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
