import type { I18nDict } from '../types';

export const FILES_TAB_DICT: I18nDict = {
  'files.page.title': {
    en: 'Generated Files Browser',
    ru: 'Просмотр сгенерированных файлов',
    es: 'Explorador de archivos generados',
  },
  'files.page.subtitle': {
    en: 'Browse all artifacts generated by the AI pipeline for each product.',
    ru: 'Просмотр всех артефактов, которые создал пайплайн для каждого продукта.',
    es: 'Explora todos los artefactos generados por el pipeline por producto.',
  },
  'files.loading.catalog': {
    en: 'Loading product catalog — {n} products per request (same idea as Pipeline first paint)',
    ru: 'Загрузка каталога продуктов — {n} шт. за запрос (как первый кадр Pipeline)',
    es: 'Cargando catálogo de productos — {n} por petición (igual que el primer pintado del Pipeline)',
  },
  'files.progress.productsInIndex': {
    en: '{loaded} / {total} products in index',
    ru: '{loaded} / {total} продуктов в индексе',
    es: '{loaded} / {total} productos en índice',
  },
  'files.progress.percentHint': {
    en: '{pct}% of catalog rows loaded — scroll the list or use "Load more" for the rest.',
    ru: '{pct}% строк каталога загружено — прокрутите список или нажмите «Загрузить ещё».',
    es: '{pct}% de filas del catálogo — desplázate o usa «Cargar más» para el resto.',
  },
  'files.waitingFirstBatch': {
    en: 'Waiting for the first batch from the server…',
    ru: 'Ожидание первой порции данных с сервера…',
    es: 'Esperando el primer lote del servidor…',
  },
  'files.error.catalog': {
    en: 'Could not load the product list (server busy or timeout). You can retry without refreshing the page.',
    ru: 'Не удалось загрузить список продуктов (сервер занят или таймаут). Можно повторить без перезагрузки страницы.',
    es: 'No se pudo cargar la lista de productos (servidor ocupado o tiempo agotado). Reintenta sin recargar.',
  },
  'files.btn.retry': { en: 'Retry', ru: 'Повторить', es: 'Reintentar' },
  'files.empty.noProducts': {
    en: 'No products found. Create a product first.',
    ru: 'Продукты не найдены. Сначала создайте продукт.',
    es: 'No hay productos. Crea uno primero.',
  },
  'files.loading.moreProducts': {
    en: 'Loading more products…',
    ru: 'Загрузка ещё продуктов…',
    es: 'Cargando más productos…',
  },
  'files.progress.rowsLoaded': {
    en: '{n} rows loaded so far',
    ru: 'Уже загружено строк: {n}',
    es: '{n} filas cargadas hasta ahora',
  },
  'files.catalog.partialHint': {
    en: 'Not all products are loaded yet — scroll the list or use "Load more" below.',
    ru: 'Не все продукты загружены — прокрутите список или нажмите «Загрузить ещё» ниже.',
    es: 'Aún no están todos los productos — desplázate o usa «Cargar más» abajo.',
  },
  'files.products.heading': { en: 'Products', ru: 'Продукты', es: 'Productos' },
  'files.products.searchPlaceholder': {
    en: 'Search products…',
    ru: 'Поиск по продуктам…',
    es: 'Buscar productos…',
  },
  'files.products.allStates': {
    en: 'All states',
    ru: 'Все состояния',
    es: 'Todos los estados',
  },
  'files.products.createdFrom': {
    en: 'Created from (local day)',
    ru: 'Создано с (локальный день)',
    es: 'Creado desde (día local)',
  },
  'files.products.createdTo': {
    en: 'Created to (local day)',
    ru: 'Создано по (локальный день)',
    es: 'Creado hasta (día local)',
  },
  'files.products.showing': {
    en: 'Showing {filtered} of {loaded} loaded',
    ru: 'Показано {filtered} из {loaded} загруженных',
    es: 'Mostrando {filtered} de {loaded} cargados',
  },
  'files.products.resetFilters': {
    en: 'Reset product filters',
    ru: 'Сбросить фильтры продуктов',
    es: 'Restablecer filtros de productos',
  },
  'files.products.loadMore': {
    en: 'Load more products ({n} loaded)',
    ru: 'Загрузить ещё продуктов (загружено {n})',
    es: 'Cargar más productos ({n} cargados)',
  },
  'files.products.loadingMoreShort': {
    en: 'Loading more…',
    ru: 'Загрузка…',
    es: 'Cargando más…',
  },
  'files.desktop.selectPrompt': {
    en: 'Select a product to browse its files',
    ru: 'Выберите продукт, чтобы просмотреть файлы',
    es: 'Selecciona un producto para ver sus archivos',
  },
  'files.preview.fullscreenSandbox': {
    en: 'Full screen sandbox',
    ru: 'Песочница на весь экран',
    es: 'Sandbox pantalla completa',
  },
  'files.preview.downloadZip': {
    en: 'Download product ZIP',
    ru: 'Скачать ZIP продукта',
    es: 'Descargar ZIP del producto',
  },
  'files.preview.zipTitle': {
    en: 'ZIP: specs, code, QA, marketing/state, telemetry — factory owner export (operator+)',
    ru: 'ZIP: spec, код, QA, маркетинг/состояние, телеметрия — экспорт для владельца (operator+)',
    es: 'ZIP: specs, código, QA, marketing/estado, telemetría — export del propietario (operator+)',
  },
  'files.preview.refresh': { en: 'Refresh', ru: 'Обновить', es: 'Actualizar' },
  'files.preview.description': {
    en: 'Preview loads below. Full screen opens in this page (no popup) so the browser does not block it.',
    ru: 'Предпросмотр ниже. Полноэкранный режим — на этой странице без всплывающего окна, чтобы браузер не блокировал.',
    es: 'La vista previa está abajo. Pantalla completa en esta página (sin popup) para evitar bloqueos.',
  },
  'files.preview.zipNote': {
    en:
      '"Download product ZIP" packs the same on-disk tree as this tab (plus a pipeline snapshot in EXPORT_MANIFEST.json) — before or after storefront listing; requires operator / admin / super_admin.',
    ru:
      '«Скачать ZIP» упакует тот же дерево на диске, что видно здесь (+ снимок пайплайна в EXPORT_MANIFEST.json) до или после выкладки; нужна роль operator / admin / super_admin.',
    es:
      '«Descargar ZIP» incluye el mismo árbol en disco que esta pestaña (más snapshot del pipeline en EXPORT_MANIFEST.json) antes o después de listar en tienda; requiere operator / admin / super_admin.',
  },
  'files.sandbox.starting': {
    en: 'Starting sandbox…',
    ru: 'Запуск песочницы…',
    es: 'Iniciando sandbox…',
  },
  'files.sandbox.retry': {
    en: 'Retry',
    ru: 'Повторить',
    es: 'Reintentar',
  },
  'files.sandbox.iframePreview': {
    en: 'Sandbox preview',
    ru: 'Предпросмотр песочницы',
    es: 'Vista previa del sandbox',
  },
  'files.sandbox.previewAfterFiles': {
    en: 'Preview is available after the file list loads.',
    ru: 'Предпросмотр доступен после загрузки списка файлов.',
    es: 'La vista previa está disponible tras cargar la lista de archivos.',
  },
  'files.sandbox.noFilesPreview': {
    en: 'No files to preview for this product.',
    ru: 'Нет файлов для предпросмотра у этого продукта.',
    es: 'Sin archivos que previsualizar para este producto.',
  },
  'files.sandbox.manualLoadExplainer': {
    en:
      'Live sandbox is not started automatically so the file list opens quickly. Load it when you need the iframe.',
    ru:
      'Живая песочница не стартует автоматически, чтобы список открывался быстрее. Запустите, когда нужен iframe.',
    es:
      'El sandbox vivo no arranca solo para que la lista cargue rápido. Ábrelo cuando necesites el iframe.',
  },
  'files.sandbox.loadPreviewBtn': {
    en: 'Load sandbox preview',
    ru: 'Загрузить предпросмотр песочницы',
    es: 'Cargar vista previa del sandbox',
  },
  'files.sandbox.fullscreenAria': {
    en: 'Sandbox full screen',
    ru: 'Песочница на весь экран',
    es: 'Sandbox pantalla completa',
  },
  'files.sandbox.fullscreenPrefix': {
    en: 'Sandbox ·',
    ru: 'Песочница ·',
    es: 'Sandbox ·',
  },
  'files.sandbox.reloadBtn': {
    en: 'Reload',
    ru: 'Перезагрузить',
    es: 'Recargar',
  },
  'files.sandbox.closeAria': {
    en: 'Close sandbox',
    ru: 'Закрыть песочницу',
    es: 'Cerrar sandbox',
  },
  'files.fileSearch.placeholder': {
    en: 'Search filename/path/content preview…',
    ru: 'Поиск по имени/пути/превью содержимого…',
    es: 'Buscar nombre/ruta/previsualización…',
  },
  'files.fileFilter.allCats': {
    en: 'All categories',
    ru: 'Все категории',
    es: 'Todas las categorías',
  },
  'files.fileFilter.resetSummary': {
    en: 'Reset file filters',
    ru: 'Сбросить фильтры файлов',
    es: 'Restablecer filtros de archivos',
  },
  'files.fileFilter.summary': {
    en: 'Showing {shown} of {total}',
    ru: 'Показано {shown} из {total}',
    es: 'Mostrando {shown} de {total}',
  },
  'files.truncated.hint': {
    en:
      'File list hit the per-category cap for: {cats}. Deeper paths under vendor dirs (e.g. node_modules) are skipped.',
    ru:
      'Список достиг предела по категориям: {cats}. Более глубокие пути в каталогах вроде node_modules пропущены.',
    es:
      'La lista alcanzó el límite por categoría para: {cats}. Se omiten rutas más profundas (p.ej. node_modules).',
  },
  'files.fileList.loading': {
    en: 'Loading files…',
    ru: 'Загрузка файлов…',
    es: 'Cargando archivos…',
  },
  'files.fileList.noneForProduct': {
    en: 'No files found for this product',
    ru: 'Для этого продукта файлов не найдено',
    es: 'No hay archivos para este producto',
  },
  'files.fileList.noMatchFilters': {
    en: 'No files match current filters',
    ru: 'Нет файлов по текущим фильтрам',
    es: 'Ningún archivo coincide con los filtros',
  },
  'files.fileList.filesFor': {
    en: '{n} files for ',
    ru: '{n} файл(ов) для ',
    es: '{n} archivos para ',
  },
};
